server:
  port: 8089
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service


  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: baonoob1011

  main:
    banner-mode: off
  config:
    import: "configserver:http://localhost:8881"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/baonoob

logging:
  level:
    org.springframework.cache: TRACE
