server:
  port: 8089
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service


  neo4j:
    uri: bolt://host.docker.internal:7687   # đổi localhost thành host.docker.internal
    authentication:
      username: neo4j
      password: baonoob1011

  main:
    banner-mode: off
  config:
    import: "configserver:http://host.docker.internal:8881"   # đổi localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/baonoob   # đổi localhost

logging:
  level:
    org.springframework.cache: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
