server:
  port: 8083
  servlet:
    context-path: /product

spring:
  application:
    name: product-service

  cloud:
    config:
      uri: http://host.docker.internal:8881   # đổi localhost → host.docker.internal

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/baonoob   # đổi localhost

  datasource:
    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=ProductDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  kafka:
    consumer:
      bootstrap-servers: host.docker.internal:9094   # đổi localhost
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: common.dto.ProductStockUpdateEvent

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
