server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - StripPrefix=2

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=2

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - StripPrefix=2

ipd:
  url: http://host.docker.internal:8180
  client_id: baonoob_app
  client_secret: "mjeiUzqstQQC9My31Vv06emyJHoed9BT"

app:
  api-prefix: /api/v1
